output "instance_id" {
  description = "The database instance ID"
  value       = "${aws_db_instance.default.id}"
}

output "instance_address" {
  description = "The database instance DNS, it will be randomly generated by Amazon"
  value       = "${aws_db_instance.default.address}"
}

output "instance_endpoint" {
  description = "The database instance DNS plus port number"
  value       = "${aws_db_instance.default.endpoint}"
}

output "database_name" {
  description = "The database name"
  value       = "${aws_db_instance.default.name}"
}

output "subnet_group_id" {
  description = "List of subnets of the DB"
  value       = "${aws_db_subnet_group.default.id}"
}

output "security_group_id" {
  description = "Security groups of the DB"
  value       = "${aws_security_group.default.id}"
}

output "hostname" {
  description = "Friendly hostname to access the DB"
  value       = "${join("", aws_route53_record.default.fqdn)}"
}

output "alias_url" {
  description = "URL of the DB for programmatic uses"
  value       = "postgresql://${join(" ", aws_route53_record.default.fqdn)}/${aws_db_instance.default.name}"
}

output "database_user" {
  description = "Database username"
  value       = "${random_string.rds_admin_user.result}"
  sensitive   = true
}

output "database_password" {
  description = "Database password"
  value       = "${random_string.rds_admin_password.result}"
  sensitive   = true
}
